### ISSUE TITLE
Checked 115 unique VPAs. Found None ❌

### ISSUE THREAD

**Issue by L337C0D3R** [LuD1161/upi-recon-cli#2]
Its showing this error for all the mobile numbers and email ids. (using live api key)

**Comment by LuD1161** [comment]
Hey @L337C0D3R 👋 
Thanks for testing out the tool.
You can try out few things : 
1. Increase the `timeout`. Like this : `./upi-recon-cli <MOBILE_NUMBER_HERE> --timeout 30`
<img width="825" alt="image" src="https://user-images.githubusercontent.com/17861054/168487438-4692d9a5-ecbd-41cc-9a53-2ca69f388760.png">
2. Check whether the mobile number's UPI actually exist or not 🤔 
Can you post a screenshot of the error message ?

**Comment by LuD1161** [comment]
Also, try with `checkAll` command as well 🙌 
`./upi-recon-cli checkAll <MOBILE_NUMBER>`

**Comment by L337C0D3R** [comment]
Still same issue,

![image](https://user-images.githubusercontent.com/51872799/168487998-99358346-a4ec-4215-99c9-738ccadf83d0.png)

**Comment by LuD1161** [comment]
Hey @L337C0D3R 👋 
There's a `DEBUG` mode as well. You can try that and see what's happening behind the scenes.
`DEBUG=True ./upi-recon-cli ....`

Also, I assume the number you're trying has a VPA, right ? 🤔

**Comment by L337C0D3R** [comment]
Hi,

I didn't understand how to run the debug mode in windows which you just mentioned... and yes my mobile number do have the VPA assigned to it.

I got this error on trying above command, "**DEBUG=True : The term 'DEBUG=True' is not recognized as the name of a cmdlet, function, script file, or operable program.**"

ex; `DEBUG=True ./upi.exe xxxxxxxxxx --timeout 60`

ps: i renamed the file to upi.exe so that i can easily access it.

**Comment by LuD1161** [comment]
Hey @L337C0D3R 
For windows, you need to set environment variable like this : 
`setx Debug "True"`
and then on the same command prompt window run the program as normally you would run it : 
`./upi.exe xxxxxxxxxx --timeout 30`

Also, since it's windows, maybe you need to check that it's allowed in the firewall.

If everything else fails, try running this on Gitpod, like this : [https://gitpod.io/#https://github.com/LuD1161/upi-recon-cli](https://gitpod.io/#https://github.com/LuD1161/upi-recon-cli) 
You'll get a remote terminal. Run the `make build` command there and you'd have the binary there.
<img width="1660" alt="image" src="https://user-images.githubusercontent.com/17861054/168489854-bde19e79-9516-43a3-b005-504ff4b909b6.png">

**Comment by LuD1161** [comment]
You can check this : https://github.com/LuD1161/upi-recon-cli#run-with-gitpod

**Comment by LuD1161** [comment]
Hey @L337C0D3R 👋 
Were you able to run this 🤔 ?

**Comment by LuD1161** [comment]
Hey @L337C0D3R 👋 
The tool doesn't require any key now. Can you try testing this now 🤔 

Thanks.

**Comment by L337C0D3R** [comment]
@LuD1161 sorry for the late reply, I was busy with work, I'll surely check this and let you know.

Thanks for the awesome support.

**Comment by L337C0D3R** [comment]
@LuD1161 I just checked it and I can confirm that it is indeed working!!! :)
Thanks for the awesome tool.

**Comment by LuD1161** [comment]
Thanks 😄
